### ISSUE TITLE
Mobile/tablet styling

### ISSUE THREAD

**Issue by SamuelJForrest** [SamuelJForrest/colourgrab-v2#12]
Review mobile and tablet styling for both the home and palette pages (including the modal).

Additionally, add a section the README on the responsivity tests conducted (related to #9)

**Comment by SamuelJForrest** [comment]
I have completed most of the mobile styling - the only outstanding is that bootstrap containers/rows/cols seem to make the layout overflow on smaller screens:

![colourgrab-overflow-issue-mobile](https://github.com/SamuelJForrest/colourgrab-v2/assets/25460460/f4a340ad-0b08-4835-accf-22e1063e5fdf)

**Comment by SamuelJForrest** [comment]
I have added in the following override for the Bootstrap `.container` class:

```scss
// Bootstrap overrides
.container {
    width: calc(100% - 30px);
    padding-left: 15px;
    padding-right: 15px;
}
```

This seems to have resolved the problem, and the made the mobile layout more akin to what you would expect from Bootstrap 4

![image](https://github.com/SamuelJForrest/colourgrab-v2/assets/25460460/7be60b9e-d8a3-431a-bd1d-b3f328aac310)
